[tool.briefcase]
project_name = "Grim"
bundle = "com.jamesbradbury"
version = "0.0.1"
url = "https://www.reacoma.xyz"
license = "BSD license"
author = 'Jane Developer'
author_email = "jamesbradbury93@gmail.com"

[tool.briefcase.app.grim]
formal_name = "Grim"
description = "Update manager for ReaCoMa"
icon = "src/grim/resources/grim"
sources = ['src/grim']
requires = []


[tool.briefcase.app.grim.macOS]
requires = [
    'toga-cocoa>=0.3.0.dev20',
]

[tool.briefcase.app.grim.linux]
requires = [
    'toga-gtk>=0.3.0.dev20',
]
system_requires = [
    'libgirepository1.0-dev',
    'libcairo2-dev',
    'libpango1.0-dev',
    'libwebkitgtk-3.0-0',
    'gir1.2-webkit-3.0',
]

[tool.briefcase.app.grim.windows]
requires = [
    'toga-winforms>=0.3.0.dev20',
]

# Mobile deployments
[tool.briefcase.app.grim.iOS]
requires = [
    'toga-iOS>=0.3.0.dev20',
]

[tool.briefcase.app.grim.android]
requires = [
    'toga-android>=0.3.0.dev20',
]
